apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: ie18we5i6-java-quarkus
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.95a84e60-e84a-4a17-ae36-d4277030b8fc.prod.konfluxeaas.com/rhtap/rhtap-qe-java-quarkus:14aaf722d2636d7f4345a4743b9808042994131d@sha256:fc7f7e7fdce7c7e56b4fd6e1629cd1cb25207b8d8ab75e7cdfd61f10007283ec
          name: container-image
