apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ie18we5i6-java-quarkus
  janus-idp.io/tekton: ie18we5i6-java-quarkus
  backstage.io/kubernetes-id: ie18we5i6-java-quarkus
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ie18we5i6-java-quarkus
resources:
- deployment.yaml
- route.yaml
- service.yaml
